[package]
name = "afterthought"
version = "0.1.0"
authors = ["Geoffrey Mon <geofbot@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[build-dependencies]
lalrpop = { version = "0.19.0", features = ["lexer"] }

[dependencies]
lalrpop-util = "0.19.0"
regex = "1"
