[package]
name = "afterthought"
version = "0.1.0"
authors = ["Geoffrey Mon <geofbot@gmail.com>"]
edition = "2018"

[build-dependencies]
lalrpop = "0.19.0"

[dependencies]
lalrpop-util = "0.19.0"
regex = "1"
